"""The conversation graph: six nodes, and the edges that make routing visible.

    START
      |
    load_context          history + rolling summary for this session
      |
    route_backend         cloud by default; local on no-key / parked cloud
      |
      +--[select_backend]--> generate_cloud --[after_cloud]--+--> generate_local
      |                                                      |
      +--[select_backend]--> generate_local <----------------+
                                  |
                                guard      <--------------------+
                                  |                             |
                                  +--[after_guard]--> regenerate on the same
                                  |                   route (budget: 1)
                                finalize
                                  |
                              update_memory
                                  |
                                 END

Two things are deliberate about the shape:

Every backend decision is an edge, never an `if` inside a node. "Which model
answered this turn, and why" is then readable from the graph and from
`state["route"]` instead of from control flow, which is the reason for putting
the turn in a graph in the first place.

The retry is a cycle back into generation rather than a second call inside
`guard`. A regenerated reply is generated by the same node, with the same
prompt assembly and the same streaming, so it cannot quietly behave differently
from a first attempt. `regenerate_count` bounds the cycle.
"""
from __future__ import annotations

import logging
import uuid
from collections.abc import AsyncIterator

from langgraph.graph import END, START, StateGraph

from brain.graph.deps import GraphDeps
from brain.graph.nodes.finalize import make_finalize
from brain.graph.nodes.generate import make_generate
from brain.graph.nodes.guard import after_guard, make_guard
from brain.graph.nodes.load_context import make_load_context
from brain.graph.nodes.route_backend import (
    CLOUD_NODE,
    LOCAL_NODE,
    after_cloud,
    make_route_backend,
    select_backend,
)
from brain.graph.nodes.update_memory import make_update_memory
from brain.graph.state import MitsukaState, new_state
from schemas.vad import VADScores

logger = logging.getLogger(__name__)


def build_graph(deps: GraphDeps):
    """Compile the turn graph over one set of dependencies."""
    builder = StateGraph(MitsukaState)

    builder.add_node("load_context", make_load_context(deps))
    builder.add_node("route_backend", make_route_backend(deps))
    builder.add_node(CLOUD_NODE, make_generate(deps, route="cloud"))
    builder.add_node(LOCAL_NODE, make_generate(deps, route="local"))
    builder.add_node("guard", make_guard(deps))
    builder.add_node("finalize", make_finalize(deps))
    builder.add_node("update_memory", make_update_memory(deps))

    builder.add_edge(START, "load_context")
    builder.add_edge("load_context", "route_backend")
    builder.add_conditional_edges(
        "route_backend", select_backend, {CLOUD_NODE: CLOUD_NODE, LOCAL_NODE: LOCAL_NODE}
    )
    builder.add_conditional_edges(
        CLOUD_NODE, after_cloud, {LOCAL_NODE: LOCAL_NODE, "guard": "guard"}
    )
    builder.add_edge(LOCAL_NODE, "guard")
    builder.add_conditional_edges(
        "guard",
        after_guard,
        {CLOUD_NODE: CLOUD_NODE, LOCAL_NODE: LOCAL_NODE, "finalize": "finalize"},
    )
    builder.add_edge("finalize", "update_memory")
    builder.add_edge("update_memory", END)

    return builder.compile()


class MitsukaGraph:
    """One compiled graph plus the two ways a caller consumes a turn.

    `ainvoke` and `astream` run the identical graph. The only difference is
    whether the custom stream channel is being read, which is what lets
    `/v1/chat` and `/v1/chat/stream` share every line of turn logic.
    """

    def __init__(self, deps: GraphDeps) -> None:
        self.deps = deps
        self.app = build_graph(deps)

    @staticmethod
    def _initial(
        user_text: str,
        session_id: str,
        turn_id: str | None,
        user_vad: VADScores | None,
        *,
        streaming: bool = False,
    ) -> MitsukaState:
        state = new_state(
            user_text=user_text,
            session_id=session_id,
            turn_id=turn_id or str(uuid.uuid4()),
            user_vad=user_vad,
        )
        state["streaming"] = streaming
        return state

    async def ainvoke(
        self,
        user_text: str,
        session_id: str = "default",
        turn_id: str | None = None,
        user_vad: VADScores | None = None,
    ) -> MitsukaState:
        """Run a turn and return the finished state. `final_reply` is the answer."""
        return await self.app.ainvoke(
            self._initial(user_text, session_id, turn_id, user_vad, streaming=False)
        )

    async def astream(
        self,
        user_text: str,
        session_id: str = "default",
        turn_id: str | None = None,
        user_vad: VADScores | None = None,
    ) -> AsyncIterator[tuple[str, object]]:
        """Yield ("delta", text) as sentences clear the guard, then ("state", state).

        The final ("state", ...) carries the same finished state `ainvoke`
        returns, so a streaming caller still gets `flags`, `route` and the
        assembled `final_reply` without running anything twice.
        """
        final: MitsukaState | None = None
        async for mode, payload in self.app.astream(
            self._initial(user_text, session_id, turn_id, user_vad, streaming=True),
            stream_mode=["custom", "values"],
        ):
            if mode == "custom":
                delta = payload.get("delta") if isinstance(payload, dict) else None
                if delta:
                    yield "delta", delta
            elif mode == "values":
                final = payload  # type: ignore[assignment]
        if final is not None:
            yield "state", final
