from __future__ import annotations

from typing import Annotated, Any
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class RetrievedDoc(TypedDict):
    doc_id: str
    content: str
    score: float
    metadata: dict[str, Any]


class BrainState(TypedDict):
    # Conversation history — add_messages reducer appends instead of overwriting
    messages: Annotated[list[BaseMessage], add_messages]

    # Current user turn
    query: str

    # Variants generated by LLM for multi-query retrieval
    generated_queries: list[str]

    # Raw retrieval results before ranking
    retrieved_docs: list[RetrievedDoc]

    # Merged, ranked context string injected into the prompt
    context: str

    # Final LLM answer
    response: str

    # Whether to run RAG retrieval (set by should_rag_node heuristic)
    use_rag: bool

    # Routing flag set by decide_node
    should_save_facts: bool
